[package]
name = "dots_and_boxes"
version = "0.1"
lean_version = "nightly-2018-04-20"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "e5d5abd9fe844b1c40267b937b8e0fbabd663d39"}
